---
name: node-exporter

instance_groups:
  - name: node-exporter
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: node_exporter
        release: node-exporter

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: node-exporter
  version: 5.2.0
  url: https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/download/v5.2.0/node-exporter-5.2.0.tgz
  sha1: ebed686ed9f2e8e2b6f505862ea1fccfe1e2a880
